# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_dash', '0023_auto_20151208_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='agent_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='agent_phone',
        ),
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs_dash.Contact', verbose_name=b'Contact'),
        ),
    ]
